OrdererOrgs:
- Name: Orderer
  Domain: example.com
  Specs:
    - Hostname: slave-30
    - Hostname: slave-31
PeerOrgs:
- Name: Org1
  Domain: example.com
  EnableNodeOUs: true
  Specs:
    - Hostname: ciidaa
    - Hostname: slave-6
    - Hostname: slave-5
    
    - Hostname: slave-7
    
  Users:
    Count: 1
